description: "Управление пользователями"
/{phone}:
    uriParameters:
        phone:
            description: "Телефон пользователя"
            type: integer
    delete:
        securedBy: [bearerAuth]
        description: "Удалить пользователя"
        is: !include /../../../vendor/zndoc/rest-api/src/is/delete.raml
