description: "Изменить пароль"
put:
    securedBy: [Auth]
    description: "Изменить пароль"
    is: !include /../../../vendor/yii2bundle/yii2-rest/src/domain/docs/is/update.raml
    body:
        application/json:
            example: !include example/password/update-request-body.json