<?php

namespace yubundle\account\domain\v2\services;

use App;
use yii\web\ForbiddenHttpException;
use yii2lab\applicationTemplate\common\enums\ApplicationPermissionEnum;
use yubundle\account\domain\v2\enums\AccountConfirmActionEnum;
use yii2rails\extension\common\exceptions\AlreadyExistsException;
use yubundle\account\domain\v2\enums\RegistrationAccessEnum;
use yubundle\account\domain\v2\exceptions\ConfirmAttemptException;
use yubundle\account\domain\v2\forms\registration\PersonInfoForm;
use yubundle\account\domain\v2\interfaces\services\RegistrationInterface;
use yubundle\user\domain\v1\entities\PersonEntity;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii2rails\domain\exceptions\UnprocessableEntityHttpException;
use yii2rails\domain\helpers\ErrorCollection;
use yii2rails\domain\helpers\Helper;
use yii2rails\domain\services\base\BaseService;
use yii2rails\extension\common\exceptions\CreatedHttpExceptionException;
use yii2rails\extension\enum\enums\TimeEnum;
use yubundle\account\domain\v2\exceptions\ConfirmAlreadyExistsException;
use yubundle\account\domain\v2\exceptions\ConfirmIncorrectCodeException;

class RegistrationService extends BaseService implements RegistrationInterface {
	
	public $smsCodeExpire = TimeEnum::SECOND_PER_MINUTE * 30;

	public function init()
    {
        if(App::$domain->has('settings')) {
            $access = App::$domain->settings->system->oneById('account.registration.access');
            if($access != RegistrationAccessEnum::OPEN) {
                throw new ForbiddenHttpException(Yii::t('account/registration', 'close_registration_message'));
            }
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function requestCodeWithPersonInfo(PersonInfoForm $model) {
        $model->scenario = PersonInfoForm::SCENARIO_PERSON_INFO;
        $this->_requestCode($model);
    }

	public function requestCode(PersonInfoForm $model) {
		$model->scenario = PersonInfoForm::SCENARIO_REQUEST_CODE;
        $this->_requestCode($model);
    }

    private function _requestCode(PersonInfoForm $model) {
        if(!$model->validate()) {
            throw new UnprocessableEntityHttpException($model);
        }
        $this->checkExistsByPhoneAndLogin($model);
        try {
            App::$domain->account->confirm->send($model->phone, AccountConfirmActionEnum::REGISTRATION, $this->smsCodeExpire);
        } catch(ConfirmAlreadyExistsException $e) {
            throw new CreatedHttpExceptionException(Yii::t('account/registration', 'user_already_exists_but_not_activation'));
        }
    }
	
	public function verifyCode(PersonInfoForm $model) {
		$model->scenario = PersonInfoForm::SCENARIO_VERIFY_CODE;
        if(!$model->validate()) {
            throw new UnprocessableEntityHttpException($model);
        }

		$this->checkExistsByPhoneAndLogin($model);

        try {
            App::$domain->account->confirm->verifyCode($model->phone, AccountConfirmActionEnum::REGISTRATION, $model->activation_code);
        } catch(NotFoundHttpException $e) {
	        throw new NotFoundHttpException(Yii::t('account/registration', 'temp_user_not_found'), 0, $e);
        } catch(ConfirmIncorrectCodeException|ConfirmAttemptException $e) {
            throw new ConfirmIncorrectCodeException(Yii::t('account/registration', 'invalid_activation_code'), 0, $e);
        }
    }
	
	public function createAccountWeb(PersonInfoForm $model) {
		$model->scenario = PersonInfoForm::SCENARIO_CREATE_ACCOUNT;
        if(!$model->validate()) {
            throw new UnprocessableEntityHttpException($model);
        }

        if(\App::$domain->account->auth->isGuest()) {
            $isAllow = false;
        } else {
            $isAllow = \App::$domain->rbac->manager->isAllow([ApplicationPermissionEnum::ACCOUNT_MANAGE]);
        }
        if(!$isAllow) {
            \App::$domain->account->registration->verifyCode($model);
        }

        $this->checkExistsByPhoneAndLogin($model);

        // check exists
        // verify
        // create account
        $entity = App::$domain->account->login->createWeb($model);
        App::$domain->account->confirm->delete($model->phone, AccountConfirmActionEnum::REGISTRATION);
        
        return $entity;
    }
	
	private function checkExistsByPhoneAndLogin(PersonInfoForm $model) {
		if(App::$domain->user->person->isExistsByPhone($model->phone)) {
			$model->addError('phone', Yii::t('account/registration', 'user_already_exists_and_activated'));
			throw new UnprocessableEntityHttpException($model);
		}
		if(App::$domain->account->login->isExistsByLogin($model->login)) {
			$model->addError('login', Yii::t('account/registration', 'user_already_exists_and_activated'));
			throw new UnprocessableEntityHttpException($model);
		}
	}

}
